export const useRoster = () => {
  const headCoaches = [
    {
      firstName: "Mike",
      lastName: "Vavrek",
      positions: ["HC"],
    },
  ];

  const assistantCoaches = [
    {
      firstName: "Mike",
      lastName: "Hensler",
      positions: ["AC"],
    },
  ];

  const managers = [
    {
      firstName: "Aya Al",
      lastName: "Tekreeti",
      positions: ["M"],
      gradYear: 2024,
    },
    {
      firstName: "Patricia",
      lastName: "Galas",
      positions: ["M"],
      gradYear: 2025,
    },
  ];

  const players = [
    {
      id: 1,
      jerseyNumber: 5,
      firstName: "Lucy",
      lastName: "Auth",
      positions: ["DS", "S"],
      gradYear: 2024,
      height: 64,
    },
    {
      id: 2,
      jerseyNumber: 15,
      firstName: "Rachel",
      lastName: "Bartels",
      positions: ["MH", "OPP"],
      gradYear: 2027,
      height: 68,
    },
    {
      id: 3,
      jerseyNumber: 19,
      firstName: "Grace",
      lastName: "Carver",
      positions: ["OH", "DS"],
      gradYear: 2026,
      height: 68,
    },
    {
      id: 4,
      jerseyNumber: 24,
      firstName: "Aria",
      lastName: "Casillas",
      positions: ["S", "OPP", "MH"],
      gradYear: 2027,
      height: 70,
    },
    {
      id: 5,
      firstName: " Grace",
      lastName: "Castaldo",
      positions: ["OH", "DS"],
      gradYear: 2027,
      height: 64,
    },
    {
      id: 6,
      jerseyNumber: 9,
      firstName: "Katelyn",
      lastName: "Clark",
      positions: ["MH", "OPP"],
      gradYear: 2024,
      height: 71,
    },
    {
      id: 7,
      jerseyNumber: 25,
      firstName: "Nola",
      lastName: "Ebberts",
      positions: ["MH", "OPP"],
      gradYear: 2027,
      height: 69,
    },
    {
      id: 8,
      jerseyNumber: 3,
      firstName: "Carmen",
      lastName: "Forsythe",
      positions: ["DS"],
      gradYear: 2025,
      height: 64,
    },
    {
      id: 9,
      jerseyNumber: 22,
      firstName: "Gabriella",
      lastName: "Frank",
      positions: ["MH"],
      gradYear: 2026,
      height: 68,
    },
    {
      id: 10,
      jerseyNumber: 23,
      firstName: "Mia",
      lastName: "Gartley",
      positions: ["OH", "MH"],
      gradYear: 2026,
      height: 68,
    },
    {
      id: 11,
      jerseyNumber: 7,
      firstName: "Nora",
      lastName: "Hammond",
      positions: ["OH", "DS"],
      gradYear: 2025,
      height: 66,
    },
    {
      id: 12,
      firstName: " Jaynie",
      lastName: "Helsel",
      positions: ["S", "OPP"],
      gradYear: 2027,
      height: 65,
    },
    {
      id: 13,
      jerseyNumber: 21,
      firstName: "isabella",
      lastName: "Jarrett",
      positions: ["S", "OPP"],
      gradYear: 2026,
      height: 69,
    },
    {
      id: 14,
      jerseyNumber: 10,
      firstName: "Annica",
      lastName: "Kagle",
      positions: ["OPP"],
      gradYear: 2024,
      height: 71,
    },
    {
      id: 15,
      jerseyNumber: 20,
      firstName: "Donika",
      lastName: "Keo",
      positions: ["DS"],
      gradYear: 2026,
      height: 61,
    },
    {
      id: 16,
      jerseyNumber: 18,
      firstName: "Lauren",
      lastName: "Krouse",
      positions: ["DS", "S"],
      gradYear: 2025,
      height: 67,
    },
    {
      id: 17,
      jerseyNumber: 8,
      firstName: "Amalia",
      lastName: "MacDonald",
      positions: ["OH"],
      gradYear: 2025,
      height: 71,
    },
    {
      id: 18,
      firstName: " Fiona",
      lastName: "Mikita",
      positions: ["OH", "DS"],
      gradYear: 2027,
      height: 63,
    },
    {
      id: 19,
      jerseyNumber: 13,
      firstName: "Eden",
      lastName: "Palladini",
      positions: ["OH", "DS"],
      gradYear: 2025,
      height: 65,
    },
    {
      id: 20,
      jerseyNumber: 6,
      firstName: "Ella",
      lastName: "Palmer",
      positions: ["OH", "DS", "OPP"],
      gradYear: 2026,
      height: 65,
    },
    {
      id: 21,
      jerseyNumber: 12,
      firstName: "Vanessa",
      lastName: "Pickett",
      positions: ["S"],
      gradYear: 2025,
      height: 68,
    },
    {
      id: 22,
      jerseyNumber: 4,
      firstName: "Mia Rosa",
      lastName: "Pugliano",
      positions: ["MH", "DS"],
      gradYear: 2024,
      height: 65,
    },
    {
      id: 23,
      jerseyNumber: 16,
      firstName: "Keira",
      lastName: "Sanner",
      positions: ["OH", "DS"],
      gradYear: 2025,
      height: 67,
    },
    {
      id: 24,
      jerseyNumber: 1,
      firstName: "Maya",
      lastName: "Sidani",
      positions: ["DS"],
      gradYear: 2027,
      height: 64,
    },
    {
      id: 25,
      jerseyNumber: 2,
      firstName: "Cadence",
      lastName: "Stancil",
      positions: ["DS"],
      gradYear: 2027,
      height: 66,
    },
    {
      id: 26,
      jerseyNumber: 17,
      firstName: "Isabella",
      lastName: "Viola",
      positions: ["MH", "OPP"],
      gradYear: 2024,
      height: 69,
    },
    {
      id: 27,
      jerseyNumber: 14,
      firstName: "Leah",
      lastName: "Weisser",
      positions: ["S", "OPP", "OH"],
      gradYear: 2026,
      height: 68,
    },
  ];

  return {
    headCoaches,
    assistantCoaches,
    managers,
    players
  };
}
